### Signup
POST http://127.0.0.1:5000/api/auth/signup
Content-Type: application/json
Origin: http://localhost:5173

{
    "username": "testuser",
    "password": "testpassword123"
}

### Login
POST http://127.0.0.1:5000/api/auth/login
Content-Type: application/json
Origin: http://localhost:5173

{
    "username": "testuser",
    "password": "testpassword123"
}

### Password Change
POST http://127.0.0.1:5000/api/auth/change-password
Content-Type: application/json
Origin: http://localhost:5173

{
    "old_password": "testpassword123",
    "new_password": "testpassword1234"
}


### User Detail
GET http://127.0.0.1:5000/api/auth/detail
Content-Type: application/json
Origin: http://localhost:5173


### Logout
POST http://127.0.0.1:5000/api/auth/logout
Content-Type: application/json
Origin: http://localhost:5173


### Delete User
DELETE http://127.0.0.1:5000/api/auth/delete
Content-Type: application/json
Origin: http://localhost:5173