### GET デバイス一覧取得
GET http://127.0.0.1:5000/api/room/devices
Content-Type: application/json
Origin: http://localhost:5173

### POST デバイス作成
POST http://127.0.0.1:5000/api/room/devices
Content-Type: application/json
Origin: http://localhost:5173

{
  "name": "device4"
}

### GET デバイス詳細取得
GET http://127.0.0.1:5000/api/room/devices/38845969-068e-4898-a6a7-48fef4f0897d
Content-Type: application/json
Origin: http://localhost:5173

### PUT デバイス更新
PUT http://127.0.0.1:5000/api/room/devices/38845969-068e-4898-a6a7-48fef4f0897d
Content-Type: application/json
Origin: http://localhost:5173

{
    "name": "device3"
}

### DELETE デバイス削除
DELETE http://127.0.0.1:5000/api/room/devices/38845969-068e-4898-a6a7-48fef4f0897d
Content-Type: application/json
Origin: http://localhost:5173